//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

using ReceiptManagement.Common.Entities;

namespace ReceiptManagement.Core.Model
{
    public partial class OrmsContext : ObjectContext
    {
        internal const string ContainerName    = "OrmsContext";
        internal const string ConnectionString = "name=OrmsContext";
    	
    	private const string ConnectionStringTemplate = 
    							@"metadata=res://*/Model.OrmsModel.csdl|res://*/Model.OrmsModel.ssdl|res://*/Model.OrmsModel.msl;
                                  provider=System.Data.SqlClient;
                                  provider connection string='{0};MultipleActiveResultSets=True'";
    
        #region Constructors
    
        private OrmsContext()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		//: turned off proxy creation for using this context object in MVC
            this.ContextOptions.ProxyCreationEnabled = false;
    
        }
    
    	internal OrmsContext(string connectionString)
            : base(string.Format(ConnectionStringTemplate, connectionString), ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		//: turned off proxy creation for using this context object in MVC
            this.ContextOptions.ProxyCreationEnabled = false;
    
        }
    
        private OrmsContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		//: turned off proxy creation for using this context object in MVC
            this.ContextOptions.ProxyCreationEnabled = false;
    
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<EventsInfo> EventsInfoes
        {
            get { return _eventsInfoes  ?? (_eventsInfoes = CreateObjectSet<EventsInfo>("EventsInfoes")); }
        }
        private ObjectSet<EventsInfo> _eventsInfoes;
    
        public ObjectSet<EventStatus> EventStatuses
        {
            get { return _eventStatuses  ?? (_eventStatuses = CreateObjectSet<EventStatus>("EventStatuses")); }
        }
        private ObjectSet<EventStatus> _eventStatuses;
    
        public ObjectSet<Image> Images
        {
            get { return _images  ?? (_images = CreateObjectSet<Image>("Images")); }
        }
        private ObjectSet<Image> _images;
    
        public ObjectSet<ImageType> ImageTypes
        {
            get { return _imageTypes  ?? (_imageTypes = CreateObjectSet<ImageType>("ImageTypes")); }
        }
        private ObjectSet<ImageType> _imageTypes;
    
        public ObjectSet<My_Products_Services> My_Products_Services
        {
            get { return _my_Products_Services  ?? (_my_Products_Services = CreateObjectSet<My_Products_Services>("My_Products_Services")); }
        }
        private ObjectSet<My_Products_Services> _my_Products_Services;
    
        public ObjectSet<PeriodType> PeriodTypes
        {
            get { return _periodTypes  ?? (_periodTypes = CreateObjectSet<PeriodType>("PeriodTypes")); }
        }
        private ObjectSet<PeriodType> _periodTypes;
    
        public ObjectSet<Product_Service_Categories> Product_Service_Categories
        {
            get { return _product_Service_Categories  ?? (_product_Service_Categories = CreateObjectSet<Product_Service_Categories>("Product_Service_Categories")); }
        }
        private ObjectSet<Product_Service_Categories> _product_Service_Categories;
    
        public ObjectSet<Product_Service_Images> Product_Service_Images
        {
            get { return _product_Service_Images  ?? (_product_Service_Images = CreateObjectSet<Product_Service_Images>("Product_Service_Images")); }
        }
        private ObjectSet<Product_Service_Images> _product_Service_Images;
    
        public ObjectSet<Product_Service_Sections> Product_Service_Sections
        {
            get { return _product_Service_Sections  ?? (_product_Service_Sections = CreateObjectSet<Product_Service_Sections>("Product_Service_Sections")); }
        }
        private ObjectSet<Product_Service_Sections> _product_Service_Sections;
    
        public ObjectSet<Product_Service_SubCategories> Product_Service_SubCategories
        {
            get { return _product_Service_SubCategories  ?? (_product_Service_SubCategories = CreateObjectSet<Product_Service_SubCategories>("Product_Service_SubCategories")); }
        }
        private ObjectSet<Product_Service_SubCategories> _product_Service_SubCategories;
    
        public ObjectSet<Products_Services> Products_Services
        {
            get { return _products_Services  ?? (_products_Services = CreateObjectSet<Products_Services>("Products_Services")); }
        }
        private ObjectSet<Products_Services> _products_Services;
    
        public ObjectSet<ReceiptImage> ReceiptImages
        {
            get { return _receiptImages  ?? (_receiptImages = CreateObjectSet<ReceiptImage>("ReceiptImages")); }
        }
        private ObjectSet<ReceiptImage> _receiptImages;
    
        public ObjectSet<Receipt> Receipts
        {
            get { return _receipts  ?? (_receipts = CreateObjectSet<Receipt>("Receipts")); }
        }
        private ObjectSet<Receipt> _receipts;
    
        public ObjectSet<Role> Roles
        {
            get { return _roles  ?? (_roles = CreateObjectSet<Role>("Roles")); }
        }
        private ObjectSet<Role> _roles;
    
        public ObjectSet<SocialUser> SocialUsers
        {
            get { return _socialUsers  ?? (_socialUsers = CreateObjectSet<SocialUser>("SocialUsers")); }
        }
        private ObjectSet<SocialUser> _socialUsers;
    
        public ObjectSet<System_Social_UsersAssociation> System_Social_UsersAssociation
        {
            get { return _system_Social_UsersAssociation  ?? (_system_Social_UsersAssociation = CreateObjectSet<System_Social_UsersAssociation>("System_Social_UsersAssociation")); }
        }
        private ObjectSet<System_Social_UsersAssociation> _system_Social_UsersAssociation;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<WarrantyCardImage> WarrantyCardImages
        {
            get { return _warrantyCardImages  ?? (_warrantyCardImages = CreateObjectSet<WarrantyCardImage>("WarrantyCardImages")); }
        }
        private ObjectSet<WarrantyCardImage> _warrantyCardImages;
    
        public ObjectSet<WarrantyCard> WarrantyCards
        {
            get { return _warrantyCards  ?? (_warrantyCards = CreateObjectSet<WarrantyCard>("WarrantyCards")); }
        }
        private ObjectSet<WarrantyCard> _warrantyCards;

        #endregion

    
    }
}

