//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventStatus
    {
        public EventStatus()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int EventStatusId { get; set; }
        public string EventStatus1 { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
