//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public long EventId { get; set; }
        public Nullable<long> My_Product_Service_Id { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public Nullable<int> NotifyBefore_PeriodValue { get; set; }
        public Nullable<int> NotifyBefore_PeriodTypeId { get; set; }
        public Nullable<int> Reoccurance_PeriodValue { get; set; }
        public Nullable<int> Reoccurance_PeriodTypeId { get; set; }
        public Nullable<int> EventStatusId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual EventStatus EventStatus { get; set; }
        public virtual My_Products_Services My_Products_Services { get; set; }
        public virtual PeriodType PeriodType { get; set; }
        public virtual PeriodType PeriodType1 { get; set; }
        public virtual User User { get; set; }
    }
}
