//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Product_Service_Images = new HashSet<Product_Service_Images>();
            this.ReceiptImages = new HashSet<ReceiptImage>();
            this.WarrantyCardImages = new HashSet<WarrantyCardImage>();
        }
    
        public long ImageId { get; set; }
        public Nullable<int> ImageTypeId { get; set; }
        public string Title { get; set; }
        public string Path { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileFormat { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ImageType ImageType { get; set; }
        public virtual ICollection<Product_Service_Images> Product_Service_Images { get; set; }
        public virtual ICollection<ReceiptImage> ReceiptImages { get; set; }
        public virtual ICollection<WarrantyCardImage> WarrantyCardImages { get; set; }
    }
}
