//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageType
    {
        public ImageType()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int ImageTypeId { get; set; }
        public string ImageType1 { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
    }
}
