//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class My_Products_Services
    {
        public My_Products_Services()
        {
            this.Events = new HashSet<Event>();
            this.My_Products_Services1 = new HashSet<My_Products_Services>();
        }
    
        public long My_Product_Service_Id { get; set; }
        public Nullable<long> Product_Service_Id { get; set; }
        public Nullable<long> Parent_My_Product_Service_Id { get; set; }
        public Nullable<long> SectionId { get; set; }
        public Nullable<long> ReceiptId { get; set; }
        public Nullable<long> WarrantyCardId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<My_Products_Services> My_Products_Services1 { get; set; }
        public virtual My_Products_Services My_Products_Services2 { get; set; }
        public virtual Products_Services Products_Services { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual Product_Service_Sections Product_Service_Sections { get; set; }
        public virtual User User { get; set; }
        public virtual WarrantyCard WarrantyCard { get; set; }
    }
}
