//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrmsEntities : DbContext
    {
        public OrmsEntities()
            : base("name=OrmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Event> Events { get; set; }
        public DbSet<EventStatus> EventStatuses { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<ImageType> ImageTypes { get; set; }
        public DbSet<My_Products_Services> My_Products_Services { get; set; }
        public DbSet<PeriodType> PeriodTypes { get; set; }
        public DbSet<Product_Service_Categories> Product_Service_Categories { get; set; }
        public DbSet<Product_Service_Images> Product_Service_Images { get; set; }
        public DbSet<Product_Service_Sections> Product_Service_Sections { get; set; }
        public DbSet<Product_Service_SubCategories> Product_Service_SubCategories { get; set; }
        public DbSet<Products_Services> Products_Services { get; set; }
        public DbSet<ReceiptImage> ReceiptImages { get; set; }
        public DbSet<Receipt> Receipts { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SocialUser> SocialUsers { get; set; }
        public DbSet<System_Social_UsersAssociation> System_Social_UsersAssociation { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WarrantyCardImage> WarrantyCardImages { get; set; }
        public DbSet<WarrantyCard> WarrantyCards { get; set; }
    }
}
