//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodType
    {
        public PeriodType()
        {
            this.Events = new HashSet<Event>();
            this.Events1 = new HashSet<Event>();
        }
    
        public int PeriodTypeId { get; set; }
        public string Title { get; set; }
        public Nullable<int> Value { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Event> Events1 { get; set; }
    }
}
