//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Service_Images
    {
        public long Id { get; set; }
        public Nullable<long> Product_Service_Id { get; set; }
        public Nullable<long> ImageId { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Products_Services Products_Services { get; set; }
    }
}
