//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Service_SubCategories
    {
        public Product_Service_SubCategories()
        {
            this.Products_Services = new HashSet<Products_Services>();
        }
    
        public int SubCategoryId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string SubCategoryTitle { get; set; }
    
        public virtual Product_Service_Categories Product_Service_Categories { get; set; }
        public virtual ICollection<Products_Services> Products_Services { get; set; }
    }
}
