//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Service_Sections
    {
        public Product_Service_Sections()
        {
            this.My_Products_Services = new HashSet<My_Products_Services>();
        }
    
        public long SectionId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<My_Products_Services> My_Products_Services { get; set; }
    }
}
