//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Services
    {
        public Products_Services()
        {
            this.My_Products_Services = new HashSet<My_Products_Services>();
            this.Product_Service_Images = new HashSet<Product_Service_Images>();
        }
    
        public long Product_Service_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<My_Products_Services> My_Products_Services { get; set; }
        public virtual Product_Service_Categories Product_Service_Categories { get; set; }
        public virtual ICollection<Product_Service_Images> Product_Service_Images { get; set; }
        public virtual Product_Service_SubCategories Product_Service_SubCategories { get; set; }
        public virtual User User { get; set; }
    }
}
