//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialUser
    {
        public SocialUser()
        {
            this.System_Social_UsersAssociation = new HashSet<System_Social_UsersAssociation>();
        }
    
        public long SocialUserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string SocialNetworkName { get; set; }
        public string Token { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        public virtual ICollection<System_Social_UsersAssociation> System_Social_UsersAssociation { get; set; }
    }
}
