//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Events = new HashSet<Event>();
            this.My_Products_Services = new HashSet<My_Products_Services>();
            this.Products_Services = new HashSet<Products_Services>();
            this.Receipts = new HashSet<Receipt>();
            this.WarrantyCards = new HashSet<WarrantyCard>();
        }
    
        public long UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<My_Products_Services> My_Products_Services { get; set; }
        public virtual ICollection<Products_Services> Products_Services { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual Role Role { get; set; }
        public virtual System_Social_UsersAssociation System_Social_UsersAssociation { get; set; }
        public virtual ICollection<WarrantyCard> WarrantyCards { get; set; }
    }
}
