//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReceiptManagement.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyCard
    {
        public WarrantyCard()
        {
            this.My_Products_Services = new HashSet<My_Products_Services>();
            this.WarrantyCardImages = new HashSet<WarrantyCardImage>();
        }
    
        public long WarrantyCardId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> WarrantyExpireOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<My_Products_Services> My_Products_Services { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<WarrantyCardImage> WarrantyCardImages { get; set; }
    }
}
