//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ReceiptManagement.Common.Helpers.Exceptions
{
    /// <summary>
    ///	The exception thrown when an error occurs when a user isn't authorized for an action they are taking.
    /// </summary>
    [System.Serializable]
    public sealed class NotAuthorizedException : System.Exception
    {
    	#region Constructors & Factories
    
        //	Internal constructors since they shouldn't be called outside of the API.
        internal NotAuthorizedException() { }
    	internal NotAuthorizedException(System.Exception innerException) : base(innerException.Message, innerException) { }
        internal NotAuthorizedException(System.String message):base(message) { }
    		
    	/// <summary>
    	///		The factory used to a new NotAuthorizedException with inner exception.
    	/// </summary>
        public static Helpers.Exceptions.NotAuthorizedException Factory(System.Exception innerException)
    	{		
            return new Helpers.Exceptions.NotAuthorizedException(innerException);
        }
    	
    	/// <summary>
    	///		The factory used to a new NotAuthorizedException with a message.
    	/// </summary>
        public static Helpers.Exceptions.NotAuthorizedException Factory(System.String message)
    	{
            return new Helpers.Exceptions.NotAuthorizedException(message);
        }
    		
    	#endregion
    }
}
